const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'shirts',
      image: '/images/shirt1.jpg',
      price: 80,
      brand: 'Nike',
      slug: 'free-shirt',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: 60,
      brand: 'Roadster',
      slug: 'slim-shirt',
      rating: 3.5,
      numReviews: 8,
      countInStock: 30,
      description: 'A popular Shirt',
    },
    {
      name: 'Polo Shirt',
      category: 'shirts',
      image: '/images/shirt3.jpg',
      price: 100,
      brand: 'polo',
      slug: 'polo-shirt',
      rating: 4.0,
      numReviews: 9,
      countInStock: 10,
      description: 'A popular Shirt',
    },
    {
      name: 'Fit Pant',
      category: 'pants',
      image: '/images/pant1.jpg',
      price: 80,
      brand: 'fit',
      slug: 'fit-pant',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Golf Pant',
      category: 'pants',
      image: '/images/pant2.jpg',
      price: 120,
      brand: 'golf',
      slug: 'golf-pant',
      rating: 3.5,
      numReviews: 5,
      countInStock: 50,
      description: 'A popular pant',
    },
    {
      name: 'Flex Pant',
      category: 'pants',
      image: '/images/pant3.jpg',
      price: 150,
      brand: 'flex',
      slug: 'flex-pant',
      rating: 3.2,
      numReviews: 7,
      countInStock: 0,
      description: 'A ladies pant',
    },
  ],
};

export default data;
